%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/dvanbossuyt/Documents/MATLAB/Peterson_Microgrid_Matlab-v10/MG1v2 Report_DVB_second_graph.xlsx
%    Worksheet: Energy
%
% Auto-generated by MATLAB on 08-Jan-2021 17:05:55

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = "Energy";
opts.DataRange = "A1:C17";

% Specify column names and types
opts.VariableNames = ["Name", "Quantity", "Description"];
opts.VariableTypes = ["char", "double", "char"];

% Specify variable properties
opts = setvaropts(opts, "EmptyFieldRule", "auto");

% Import the data
Energy_Input = readtable(Report_Workbook, opts, "UseExcel", false);


%variable_names = categorical(Energy_Input.Variable_Name);
%variable_quantities = categorical(Energy_Input.Variable_Quantity);

%Then put here something to take the variable names and use those as
%variables to assign the values to them from the quantities.


%% Clear temporary variables
clear opts %variables
%T.Date(1:5)
PV.Area = Energy_Input.Quantity(1);
PV.eff = Energy_Input.Quantity(2);
Gens(1).Capacity = Energy_Input.Quantity(3);
Gens(1).Storage = Energy_Input.Quantity(4);
Gens(1).Efficiency = Energy_Input.Quantity(5);
Gens(1).Refuel = Energy_Input.Quantity(6);
Gens(1).PrRefuel = Energy_Input.Quantity(7);
Gens(1).RefuelTogether = Energy_Input.Quantity(8);
Gens(2).Capacity = Energy_Input.Quantity(9);
Gens(2).Storage = Energy_Input.Quantity(10);
Gens(2).Efficiency = Energy_Input.Quantity(11);
Gens(2).Refuel = Energy_Input.Quantity(12);
Gens(2).PrRefuel = Energy_Input.Quantity(13);
Gens(2).RefuelTogether = Energy_Input.Quantity(14);
BT1.Capacity = Energy_Input.Quantity(15);
% BT1.Output = BT1.Capacity*0.20;
% Test with battery output override to test impact
BT1.Output = Energy_Input.Quantity(16);
BT1.Efficiency = Energy_Input.Quantity(17); % One way efficiency. 



if 1 == 2
    %PV Data
    PV.Area = 3000; %area in m^2
    PV.eff = 0.18; %PV efficiency

    %Generator Data
    Gens(1).Capacity = 300; %kW
    Gens(1).Storage = 5300/2; %Gal
    Gens(1).Efficiency = 1/13; %(GPH/kW)
    Gens(1).Refuel = 7*24; % # of hours between refueling
    Gens(1).PrRefuel = 0.95; % Pr of Refueling each time
    Gens(1).RefuelTogether = true; %Set if refueling is together or independent
    Gens(2) = Gens(1); % Identical Generators

    %Battery Storage Capacity in kW*hr, Output in kW
    BT1.Capacity = 3000;
    % BT1.Output = BT1.Capacity*0.20;
    % Test with battery output override to test impact
    BT1.Output = 300;
    BT1.Efficiency = sqrt(0.95); % One way efficiency. 
    
else
end

