%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\rally\Google Drive\Transfer\SEP\SE3810 Thesis Workshop\Microgrid Thesis\MATLAB Model\724915TY.csv
%
% Auto-generated by MATLAB on 05-May-2019 17:23:12

%% Import Solar Data for Typical Meteological Year
opts = delimitedTextImportOptions("NumVariables", 68);

% Specify range and delimiter
opts.DataLines = [3, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["DateMMDDYYYY", "TimeHHMM", "ETRWm2", "ETRNWm2", "GHIWm2", "GHIsource", "GHIuncert", "DNIWm2", "DNIsource", "DNIuncert", "DHIWm2", "DHIsource", "DHIuncert", "GHillumlx", "GHillumsource", "Globalillumuncert", "DNillumlx", "DNillumsource", "DNillumuncert", "DHillumlx", "DHillumsource", "DHillumuncert", "Zenithlumcdm2", "Zenithlumsource", "Zenithlumuncert", "TotCldtenths", "TotCldsource", "TotClduncertcode", "OpqCldtenths", "OpqCldsource", "OpqClduncertcode", "DrybulbC", "Drybulbsource", "Drybulbuncertcode", "DewpointC", "Dewpointsource", "Dewpointuncertcode", "RHum", "RHumsource", "RHumuncertcode", "Pressurembar", "Pressuresource", "Pressureuncertcode", "Wdirdegrees", "Wdirsource", "Wdiruncertcode", "Wspdms", "Wspdsource", "Wspduncertcode", "Hvism", "Hvissource", "Hvisuncertcode", "CeilHgtm", "CeilHgtsource", "CeilHgtuncertcode", "Pwatcm", "Pwatsource", "Pwatuncertcode", "AODunitless", "AODsource", "AODuncertcode", "Albunitless", "Albsource", "Albuncertcode", "Lprecipdepthmm", "Lprecipquantityhr", "Lprecipsource", "Lprecipuncertcode"];
opts.VariableTypes = ["datetime", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "double", "categorical", "double", "double", "categorical", "double", "double", "categorical", "double", "double", "categorical", "double", "double", "categorical", "double", "double", "categorical", "double", "double", "categorical", "double", "double", "categorical", "double", "double", "categorical", "double", "double", "categorical", "double", "double", "categorical", "double", "double", "categorical", "double", "double", "double", "categorical", "double"];
opts = setvaropts(opts, 1, "InputFormat", "MM/dd/yyyy");
opts = setvaropts(opts, [2, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 67], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Setup rules for import
opts.ImportErrorRule = "error";
opts = setvaropts(opts, [4, 5, 8], "FillValue", 0);

% Set Date to Import
opts.SelectedVariableNames = ["DNIWm2"];

% Import the data
solar = readtable("724915TY.csv", opts);

% Convert to output type

solar = table2array(solar);

% Clear temporary variables
clear opts