%% Import data from text file
% Script for importing data from the following text file:
%
% Auto-generated by MATLAB on 10-May-2019 13:16:38

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["DateTime", "ElectricityFacilitykWHourly", "FansElectricitykWHourly", "CoolingElectricitykWHourly", "HeatingElectricitykWHourly", "InteriorLightsElectricitykWHourly", "InteriorEquipmentElectricitykWHourly", "GasFacilitykWHourly", "HeatingGaskWHourly", "WaterHeaterWaterSystemsGaskWHourly", "ElectricityFacilitykWMonthly"];
opts.SelectedVariableNames = ["ElectricityFacilitykWHourly", "InteriorLightsElectricitykWHourly", "InteriorEquipmentElectricitykWHourly"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, [1, 11], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 11], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Setup rules for import
opts.ImportErrorRule = "error";
opts = setvaropts(opts, [2,  3,  4,  5,  6,  7,  8,  9, 10], "FillValue", 0);

% Import the data
RefLargeOfficeLoads = readtable("RefBldgLargeOfficeNew2004_7.1_5.0_3C_USA_CA_SAN_FRANCISCO.csv", opts);
RefLargeOfficeLoads.Properties.VariableNames = {'Normal','Lights','Equipment'};
RefLargeOfficeLoads.Critical = 0.5*RefLargeOfficeLoads.Lights + .67*RefLargeOfficeLoads.Equipment;

RefMedOfficeLoads = readtable("RefBldgMediumOfficeNew2004_7.1_5.0_3C_USA_CA_SAN_FRANCISCO.csv", opts);
RefMedOfficeLoads.Properties.VariableNames = {'Normal','Lights','Equipment'};
RefMedOfficeLoads.Critical = 0.5*RefMedOfficeLoads.Lights + .67*RefMedOfficeLoads.Equipment;

RefSmallOfficeLoads = readtable("RefBldgSmallOfficeNew2004_7.1_5.0_3C_USA_CA_SAN_FRANCISCO.csv", opts);
RefSmallOfficeLoads.Properties.VariableNames = {'Normal','Lights','Equipment'};
RefSmallOfficeLoads.Critical = 0.5*RefSmallOfficeLoads.Lights + .67*RefSmallOfficeLoads.Equipment;

RefWarehouseLoads = readtable("RefBldgWarehouseNew2004_7.1_5.0_3C_USA_CA_SAN_FRANCISCO.csv", opts);
RefWarehouseLoads.Properties.VariableNames = {'Normal','Lights','Equipment'};
RefWarehouseLoads.Critical = 0.5*RefWarehouseLoads.Lights + .67*RefWarehouseLoads.Equipment;


%% Clear temporary variables
clear opts