%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\rally\Google Drive\Transfer\SEP\SE3810 Thesis Workshop\Microgrid Thesis\MATLAB Model\724915_2000_solar.csv
%
% Auto-generated by MATLAB on 05-May-2019 18:28:13

%% Import NPS Solar Data for Specific Year
opts = delimitedTextImportOptions("NumVariables", 43);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["YYYYMMDD", "HHMMLST", "Zenithdeg", "Azimuthdeg", "ETRWhm2", "ETRNWhm2", "SUNYGloWhm2", "SUNYGloFlg", "SUNYGloUnc", "SUNYDirWhm2", "SUNYDirFlg", "SUNYDirUnc", "SUNYDifWhm2", "SUNYDifFlg", "SUNYDifUnc", "METSTATGloWhm2", "METSTATGloUnc", "METSTATDirWhm2", "METSTATDirUnc", "METSTATDifWhm2", "METSTATDifUnc", "METSTATCSKYGloWhm2", "METSTATCSKYGloUnc", "METSTATCSKYDirWhm2", "METSTATCSKYDirUnc", "METSTATCSKYDifWhm2", "METSTATCSKYDifUnc", "MeasGloWhm2", "MeasGloFlg", "MeasDirWhm2", "MeasDirFlg", "MeasDifWhm2", "MeasDifFlg", "PrecipWatcm", "PrecipWatFlg", "AODunitless", "AODFlg", "AODRANunitless", "AODRANFlg", "Ozonecm", "OzoneFlg", "Albedounitless", "AlbedoFlg"];
opts.VariableTypes = ["datetime", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 1, "InputFormat", "yyyy-MM-dd");
opts = setvaropts(opts, 2, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Select Solar Data Type to Import
opts.SelectedVariableNames = "SUNYDirWhm2";

% Setup rules for import
opts.ImportErrorRule = "error";
opts = setvaropts(opts, [3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43], "FillValue", 0);

% Import the data
solar = readtable("724915_"+year.run+"_solar.csv", opts);

% Convert to output type
solar = table2array(solar);

% Clear temporary variables
clear opts